We are going to register an LDAP authentication provider. We use http://www.ldaptive.org[Ldaptive].

____
Ldaptive is a simple, extensible Java API for interacting with LDAP servers. It was designed to provide easy LDAP integration for application developers.
____

Modify `build.gradle` file to add the dependency:

[source,groovy]
.build.gradle
----
ext {
include::{sourceDir}/build.gradle[tag=extLdap]
}
dependencies {
...
..
.
include::{sourceDir}/build.gradle[tag=ldap]
}
----

We are going to use an https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/[Online LDAP test server] for this guide.

Create several configuration properties matching those of the test LDAP Server.

[source,groovy]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=ldap]
----

Create an implementation of `io.micronaut.security.authentication.AuthenticationProvider`

[source,groovy]
.src/main/groovy/example/micronaut/providers/LdapService.groovy
----
include::{sourceDir}/src/main/groovy/example/micronaut/providers/LdapService.groovy[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton.
<2> Implement `io.micronaut.security.authentication.AuthenticationProvider`
<3> Several configuration values are injected via constructor injection.
<4> Use the `javax.annotation.PostConstruct` annotation to trigger the method execution after dependency injection is done. Typically to perform any initialization.
<5> For successful authentication, return in instance of `UserDetails`.